
    name: Deploy ke InfinityFree

    on:
      push:
        branches:
          - main

    jobs:
      deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout kode
            uses: actions/checkout@v2

          - name: Instalasi FTP Client
            run: sudo apt-get install ftp -y

          - name: Deploy ke InfinityFree
            env:
              FTP_SERVER: ${ secrets.FTP_SERVER }
              FTP_USERNAME: ${ secrets.FTP_USERNAME }
              FTP_PASSWORD: ${ secrets.FTP_PASSWORD }
            run: |
              ftp -inv $FTP_SERVER << EOF
              user $FTP_USERNAME $FTP_PASSWORD
              cd /domains/demo-disciline-devuna.ct.ws/public_html  # Path folder subdomain
              mput -O /domains/demo-disciline-devuna.ct.ws/public_html *
              bye
              EOF
    